DETAIL_TYPE_QUERY_SUBMITTED = "eventforge.query.submitted"
QUERY_SUBMITTED_SCHEMA_VERSION = "1.0"

DETAIL_TYPE_INGESTION_COMPLETED = "eventforge.ingestion.completed"
INGESTION_COMPLETED_SCHEMA_VERSION = "1.0"

DETAIL_TYPE_EMBEDDING_COMPLETED = "eventforge.embedding.completed"
EMBEDDING_COMPLETED_SCHEMA_VERSION = "1.0"

DETAIL_TYPE_KNOWLEDGE_MINED = "eventforge.knowledge.mined"
KNOWLEDGE_MINED_SCHEMA_VERSION = "1.0"

DETAIL_TYPE_RESEARCH_TASK_DISPATCHED = "eventforge.research.task.dispatched"
RESEARCH_TASK_DISPATCHED_SCHEMA_VERSION = "1.0"

DETAIL_TYPE_RESEARCH_TASK_COMPLETED = "eventforge.research.task.completed"
RESEARCH_TASK_COMPLETED_SCHEMA_VERSION = "1.0"

DETAIL_TYPE_SYNTHESIS_COMPLETED = "eventforge.synthesis.completed"
SYNTHESIS_COMPLETED_SCHEMA_VERSION = "1.0"

DETAIL_TYPE_PIPELINE_FAILED = "eventforge.pipeline.failed"
PIPELINE_FAILED_SCHEMA_VERSION = "1.0"

WORKER_NAME_INGESTION = "ingestion"
WORKER_NAME_EMBEDDING = "embedding"
WORKER_NAME_KNOWLEDGE = "knowledge"
WORKER_NAME_RESEARCH = "research"
WORKER_NAME_RESEARCH_ORCHESTRATOR = "research-orchestrator"
WORKER_NAME_SYNTHESIS = "synthesis"
WORKER_NAME_DLQ = "dlq"

# Mock embedding dimension for Phase 2 stub (OpenAI text-embedding-3-small uses 1536 in prod).
MOCK_EMBEDDING_DIMENSION = 8
MOCK_CHUNKS_PER_SOURCE = 2
MOCK_RESEARCH_TASK_COUNT = 3
