DETAIL_TYPE_QUERY_SUBMITTED = "eventforge.query.submitted"
QUERY_SUBMITTED_SCHEMA_VERSION = "1.0"

DETAIL_TYPE_INGESTION_COMPLETED = "eventforge.ingestion.completed"
INGESTION_COMPLETED_SCHEMA_VERSION = "1.0"

WORKER_NAME_INGESTION = "ingestion"
