/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Ready */
        get: operations["health_ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List User Queries */
        get: operations["list_user_queries_api_v1_queries_get"];
        put?: never;
        /** Create Query */
        post: operations["create_query_api_v1_queries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queries/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Query */
        get: operations["get_query_api_v1_queries__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queries/{job_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Query Events
         * @description Stream pipeline stage updates for a job via Server-Sent Events.
         */
        get: operations["stream_query_events_api_v1_queries__job_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api V1 Root */
        get: operations["api_v1_root_api_v1__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JobStageResponse
         * @description One pipeline stage and its execution status.
         */
        JobStageResponse: {
            /** Stage */
            stage: string;
            /** Status */
            status: string;
            /** Started At */
            started_at: string | null;
            /** Completed At */
            completed_at: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Error Detail */
            error_detail: string | null;
        };
        /**
         * LLMUsageCallResponse
         * @description One logged LLM call for a job.
         */
        LLMUsageCallResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Agent Name */
            agent_name: string;
            /** Model */
            model: string;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Cost Usd */
            cost_usd: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * LLMUsageSummaryResponse
         * @description Aggregated LLM cost and per-call breakdown for a job.
         */
        LLMUsageSummaryResponse: {
            /** Total Cost Usd */
            total_cost_usd: number;
            /** Calls */
            calls: components["schemas"]["LLMUsageCallResponse"][];
        };
        /**
         * QueryDepth
         * @description Research depth preset controlling source count and thoroughness.
         * @enum {string}
         */
        QueryDepth: "quick" | "standard" | "deep";
        /**
         * QueryDetailResponse
         * @description Full job detail including stages and optional synthesis report.
         */
        QueryDetailResponse: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Correlation Id */
            correlation_id: string;
            /** Topic */
            topic: string;
            /** Depth */
            depth: string;
            /** Status */
            status: string;
            /** Max Sources */
            max_sources: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Stages */
            stages: components["schemas"]["JobStageResponse"][];
            /** Sources */
            sources?: components["schemas"]["SourceResponse"][];
            synthesis_report?: components["schemas"]["SynthesisReportResponse"] | null;
            llm_usage: components["schemas"]["LLMUsageSummaryResponse"];
        };
        /**
         * QuerySummaryResponse
         * @description Lightweight job summary for list endpoints.
         */
        QuerySummaryResponse: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Correlation Id */
            correlation_id: string;
            /** Topic */
            topic: string;
            /** Depth */
            depth: string;
            /** Status */
            status: string;
            /** Max Sources */
            max_sources: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * SourceResponse
         * @description Web source discovered during ingestion.
         */
        SourceResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Url */
            url: string;
            /** Title */
            title: string;
            /** Snippet */
            snippet: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * SubmitQueryRequest
         * @description HTTP body for POST /api/v1/queries.
         */
        SubmitQueryRequest: {
            /** Topic */
            topic: string;
            /** @default standard */
            depth: components["schemas"]["QueryDepth"];
            /** Max Sources */
            max_sources?: number | null;
        };
        /**
         * SubmitQueryResponse
         * @description HTTP response after a query is accepted into the pipeline.
         */
        SubmitQueryResponse: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Correlation Id */
            correlation_id: string;
        };
        /**
         * SynthesisReportResponse
         * @description Final report produced by the synthesis stage.
         */
        SynthesisReportResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_user_queries_api_v1_queries_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuerySummaryResponse"][];
                };
            };
        };
    };
    create_query_api_v1_queries_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitQueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitQueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_query_api_v1_queries__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_query_events_api_v1_queries__job_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_v1_root_api_v1__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
